### ISSUE TITLE
FreeBSD 13.0 EoL since August 31, 2022

### ISSUE THREAD

**Issue by skipperTux** [virt-lightning/freebsd-cloud-images#4]
FreeBSD 13.0 is EoL since end of August 2022, current supported release is [FreeBSD 13.1](https://www.freebsd.org/releases/). Any plans to update the script and the [BSD cloud images](https://bsd-cloud-image.org/)?
The `freebsd-update` command is not very Ansible-friendly when doing release upgrades, only interactive mode is supported.

(edit) Same is true for FreeBSD 12.2 (EoL) => 12.3.

**Comment by goneri** [comment]
Thank you @skipperTux. The problem is not resolved.
